### ISSUE TITLE
"end of log" message is missing on "SHOW"

### ISSUE THREAD

**Issue by SISProject** [SISProject/SISSoftware#42]
When SHOW is selected on the SIS Client, it used to say "retrieving log", then display the log, and then say "end of log" (or something similar).  Today I noticed that the end of log is missing.  If the log is empty, all you see is "retrieving log", so it looks like the client is hung up.  This is a fairly recent bug, albeit I'm not sure what version it first appeared in.

**Comment by jschrempp** [comment]
Fixed in V 26
